// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcUvb9QnXQCocV1IFg9BBs2Og0eMH4RLQ',
    appId: '1:1028911584955:web:4a4ee408c4d31036f9fb9e',
    messagingSenderId: '1028911584955',
    projectId: 'flutter-clean-architectu-463d9',
    authDomain: 'flutter-clean-architectu-463d9.firebaseapp.com',
    databaseURL: 'https://flutter-clean-architectu-463d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-clean-architectu-463d9.appspot.com',
    measurementId: 'G-DRXTQNFV14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtYFxCbrEXHKOfc-nhgaOMhKj1EeLUQss',
    appId: '1:1028911584955:android:56de847dc6205095f9fb9e',
    messagingSenderId: '1028911584955',
    projectId: 'flutter-clean-architectu-463d9',
    databaseURL: 'https://flutter-clean-architectu-463d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-clean-architectu-463d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB372jOlLeVSAm2Qtjy9yh06vK7hla-FIk',
    appId: '1:1028911584955:ios:fb539102256a805bf9fb9e',
    messagingSenderId: '1028911584955',
    projectId: 'flutter-clean-architectu-463d9',
    databaseURL: 'https://flutter-clean-architectu-463d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-clean-architectu-463d9.appspot.com',
    androidClientId: '1028911584955-dr5egtvrthe624ul3a3rrlub2hmsep1k.apps.googleusercontent.com',
    iosClientId: '1028911584955-vunullhai6gamkc3kv666r59u3vl45p6.apps.googleusercontent.com',
    iosBundleId: 'com.bigyossapon.struccleancrudexam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB372jOlLeVSAm2Qtjy9yh06vK7hla-FIk',
    appId: '1:1028911584955:ios:fb539102256a805bf9fb9e',
    messagingSenderId: '1028911584955',
    projectId: 'flutter-clean-architectu-463d9',
    databaseURL: 'https://flutter-clean-architectu-463d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-clean-architectu-463d9.appspot.com',
    androidClientId: '1028911584955-dr5egtvrthe624ul3a3rrlub2hmsep1k.apps.googleusercontent.com',
    iosClientId: '1028911584955-vunullhai6gamkc3kv666r59u3vl45p6.apps.googleusercontent.com',
    iosBundleId: 'com.bigyossapon.struccleancrudexam',
  );
}
